### ISSUE TITLE
BFStop and PHP 7 throwing Deprecate Error

### ISSUE THREAD

**Issue by alexsmithers** [codeling/bfstop#124]
There is a problem with BFS when using PHP 7 and Joomla.  I get the error below......

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; plgSystembfstop has a deprecated constructor in D:\Data\WebSites\xxxxxxx\plugins\system\bfstop\bfstop.php on line 18

I changed the class name so it didn't match the function name to remove the error...  I do not not know if it will affect the operation... (Class name was "plgSystembfstop" and I changed it to "plgSystembfstopCls")
class plgSystembfstopCls extends JPlugin
{
    private $myapp;
    private $mydb;
    private $logger;

    function plgSystembfstop(& $subject, $config)

**Comment by codeling** [comment]
This has been fixed recently by this pull request: https://github.com/codeling/bfstop/pull/122/files
The correct fix, as can be seen there, is to rename the "plgSystembfstop" method to "__construct"

If you feel up to it, you can install the latest bfstop version by downloading the zip from https://github.com/codeling/bfstop.
Otherwise you'll have to wait for the next bfstop version (1.4.0, planned to come out some time this year, unfortunately delayed a lot due to no time on my part).

**Comment by alexsmithers** [comment]
Sweet!  Thanks..  Sorry I missed the previous ticket....

**Comment by codeling** [comment]
No problem, thanks for the report!
