### ISSUE TITLE
Anyway to see the tried passwords?

### ISSUE THREAD

**Issue by MarkA67** [codeling/bfstop#153]
I can see the username the person tried to login with, but is there anyway we can see the passwords they tried?

**Comment by codeling** [comment]
At the moment, this is not possible. See [the FAQ](https://github.com/codeling/bfstop/wiki/FAQ#why-dont-i-see-the-password-from-the-attempted-login) for more details.

I might consider adding it optionally in a future release.

**Comment by Aliasname** [comment]
It would really help to improve password complexity for frontend users.
It is also possible to use password exceptions with this information, so that no user can use one of these passwords.
If you think a step further, even a user can be notified or prompted for password renewal if the password matches a password that originates from a brute force attack.
There are many ways to increase security if you know the passwords of brute force attacks.
I hope you can include this feature in version 1.5 and not in 1.6.

**Comment by codeling** [comment]
I do see some benefit for security researchers, when applied to multiple sites, to get hold of the potential attack dictionaries currently in use.

Using these for password policies is however out of the current scope of this plugin. Also, what would in your opinion be the real benefit of using a dynamic banned password list, created from the failed login attempts at a specific Joomla! installation, over using a banned password list from known often tried passwords, or a rule-based system based on these (see e.g. https://security.stackexchange.com/questions/116780/how-to-create-dictionary-to-prevent-weak-passwords)?

**Comment by codeling** [comment]
What also has to be considered here are privacy concerns. Consider a legitimate user trying a few passwords (he potentially also uses on other sites). Then every user with access to the bfstop backend can potentially misuse these.

**Comment by codeling** [comment]
For the moment I will not implement this due it probably being classified as a information disclosure issue (see FAQ entry link above). Security researchers needing this functionality should be able to implement the functionality on their own.
