### ISSUE TITLE
Update brought down my site

### ISSUE THREAD

**Issue by rlube** [codeling/bfstop#155]
I have just updated the extension from 1.3.0 to 1.4.1 on my site, using Joomla's built-in extension updater. But it did the following and has brought the whole site down. Looks like the DB is smashed. What on earth happened? Site is www.marouka.com.au

Using newest stable version of Joomla.

Unknown column 'crdate' in 'field list' SQL=SELECT id, ipaddress, crdate from #__bfstop_whitelist WHERE (ipaddress='124.189.101.248' OR (LENGTH(ipaddress) <= 18 AND LOCATE('/', ipaddress) != 0 AND (INET_ATON('124.189.101.248') & ~((1 << (32 - SUBSTR(ipaddress, LOCATE("/", ipaddress)+1, LENGTH(ipaddress)-LOCATE("/", ipaddress))))-1)) = (INET_ATON(SUBSTR(ipaddress, 1, LOCATE("/", ipaddress)-1)) & ~((1 << (32 - SUBSTR(ipaddress, LOCATE("/", ipaddress)+1, LENGTH(ipaddress)-LOCATE("/", ipaddress))))-1))))

**Comment by codeling** [comment]
First off, sorry for the trouble caused.

The error message you state is shown on the frontend site? Then it indicates that the update of the plugin files actually did not succeed; the latest plugin version does not reference the (removed) crdate column of the whitelist table anymore. How that happened I cannot tell you (maybe some files were cannot be written to, for example because they were created by not by the user account running the webserver but by the ftp user account?)

To fix this, you need to update all plugin files to the actual latest version. Since you probably don't have access to the administrator backend, you will have to go through for example ftp or ssh to achieve this.
Download the archive for version 1.4.1 (-> https://github.com/codeling/bfstop/archive/1.4.1.zip), extract it, then go into the "bfstop-1.4.1" folder, and delete the "unittests" folder and the files "CHANGELOG", "deploy.sh", "LICENSE.txt", "README" and "update.xml", and then upload all remaining files and folders in this "bfstop-1.4.1" folder to the subfolder "plugins/system/bfstop" of your Joomla! installation.

**Comment by rlube** [comment]
Thank you, after restoring my site, I have been successful in installing 
it manually.


-- 
Ron Lubensky
Melbourne Australia
0411 412 626

**Comment by codeling** [comment]
Thanks for reporting back!

I unfortunately don't have a clue why this happened for you; but I will take this as an opportunity to build more checks into bfstop to make it more resilient against such errors!

**Comment by codeling** [comment]
With b3032b9bb0769b9f016791e02a928c0f4a7f4c01, such an error message will not appear in the frontend anymore.
However, this also means that in case of such errors, the administrator will not immediately notice them on accessing his site. To some extent this shall be remedied by #156, where I will add a warning sign in the component part if there were any errors recorded in the log file.
