### ISSUE TITLE
Counter only for invalid data

### ISSUE THREAD

**Issue by IamBelka** [codeling/bfstop#175]
Good day, is it possible to configure the plugin, in which the reverse attempt counter will be activated only when you enter incorrect data-username\password. The counter now counts logins to the account, even if the data is entered correctly

**Comment by codeling** [comment]
I think I don't understand the question - because as far as I understand, bfstop already does exactly what you are asking for:

> is it possible to configure the plugin, in which the reverse attempt counter will be activated only when you enter incorrect data-username\password.

By the "reverse attempt counter" I guess you mean the optional feature where BFStop shows how many login attempts are remaining before the user is blocked, right?
This notification should for starters *only* be shown if invalid credentials where entered, in a message region on the login page. When you log in successfully you should not get any message.

> The counter now counts logins to the account, even if the data is entered correctly

If I understand this correctly, what you currently observe BFStop doing is this: You enter valid credentials on the login page, and then you see somewhere how many times you have entered valid credentials so far. If you enter invalid credentials however, you see no message / no hint on how many remaining attempts.
Does this correctly summarize what you see? Could you maybe elaborate a bit - e.g., on: Are you able to login with valid credentials, or are you redirected back to the login page? Can you tell me where you see this number of correctly entered data? Can you give a concrete example, ideally with e.g. screenshots of the behaviour you see?

**Comment by IamBelka** [comment]
Good day, thank you for such a quick reply.
I use BFStop to control user login to the site. When you activate the "ENTER" button, a message already appears that "you have 5 attempts to enter," while the user has not yet entered the data on the site. If the data is entered correctly, the user logs on to the site, but then logs out and re-enters the data, the counter continues to count - 4-3-2-1.
But such a problem only when users log in to the site, through /administrator/index.php/ everything works correctly.

**Comment by codeling** [comment]
> When you activate the "ENTER" button, a message already appears that "you have 5 attempts to enter," while the user has not yet entered the data on the site.

I suppose you start on the login page (yourdomain.com/index.php/component/users/?view=login), right? Does the message already appear when loading the page, or does the user have to do anything? What do you mean by "activating" the ENTER button? Pressing it? If you mean pressing the Enter key, then this does submit the login form, this is a standard behavior for forms on any website. This might explain why you see the warning, because if you submit via the Enter key, this counts as a login attempt, just the same as if you would click on the "Login" button. But you said you hadn't entered anything yet, and I wonder how you could submit anything in that case, since in my Joomla installation, a local Javascript and/or some validation hints for the user/password inputs (which are embedded in the login form by Joomla itself, not by my plugin) prevent the form to be submitted with no data entered.
Could it be that you have some browser extension installed which disables javascript / this validation?
To what did you set the "Remaining attempts" setting in the plugin configuration on the "Advanced" tab?

Successful login attempts should (and do in my case) reset the number of remaining login attempts.
In your case, when do you see the message? Immediately when you navigate to the login page? When you press enter on it? Are you sure the user was properly logged in in-between?

What bfstop and Joomla version are you using? What server php version, what browser? There must be something specific about your environment causing the issue you see, because I have not heard reports about similar behavior yet from any other user!

**Comment by IamBelka** [comment]
Good day, 
Yes, the site includes the standard module "Login to the site". To log in to the site, the user clicks on the button and goes to the address component/users/?view=login&Itemid=101. In this case, the system displays the message "Empty password is invalid" and "there are 5 attempts left to enter". It is likely that this is the reason for the error-it is possible that a login request is already generated when you click on it. If I refresh the page using ctrl+f5, then bfstop also believes that there was an attempt to log in with incorrect data. 
Installed joomla 3.9.5, bfstop 1.4.1, PHP 7.2.15. Browsers-chrome, yandex. Without additional extensions and on different computers. bfstop is configured as standard with a limit of 5 attempts. 
The problem is that I'm new to this business and I may not catch the subtleties.

**Comment by codeling** [comment]
For me, the "Login" module already contains user and password inputs, but yes, here the javascript / validation hints are missing. You don't see any username/password inputs in that module? Then there seems to be something wrong with your template (most likely), or the Login module itself is faulty (less likely). The Login button on that module triggers a form submit (meaning a login attempt), but in your case with no username and password (when the respective inputs aren't shown nothing can be entered).

If you can't easily fix the template (/the module), as a workaround, I would suggest that instead of the module, you use a single article module with a link directly to the login page.

If you press Ctrl+F5, and you came to the current site by clicking Enter / submitting a form via a button, then browsers typically ask whether you want to re-submit the form data - and if you click yes there, then of course, this counts as an additional login attempt - the server just sees the additional request, and it wouldn't make sense to try and check whether this might be a refresh, because the credentials are checked in that request, meaning, functionally, it is indistinguishable from another login attempt, and, if exempted, could allow attackers additional, "free" attempts.

Joomla 3.9.5 is rather outdated, I recommend updating to the latest 3.9.19.

**Comment by codeling** [comment]
Actually, correction to my previous statement that a valid login would reset the counter: this is not the case; intentionally so, otherwise an attacker could register an account, then try a few credentials, log in successfully with his registered account, and then continue with more attempts.

The main problem in this case I think though is the missing input for username and password in the Login module!

**Comment by IamBelka** [comment]
I apologize for bothering you, and thank you for your answers and help. I will try to fix the error

**Comment by codeling** [comment]
No worries, it didn't bother me ;)
Turns out in the process, I re-learned something about my own software - it's been a while since I last updated it...
