### ISSUE TITLE
Blocked whitelisted IP and can`t unblock.

### ISSUE THREAD

**Issue by SuperSonic45** [codeling/bfstop#176]
I have added IP address in Whitelist section a few weeks ago and today that whitelisted IP was blocked, so now i got same IP in "Whitelist" and "Blocked IPs (database)" sections. Furthermore i can not unblock it. Then i set checkbox on that IP in "Blocked IPs (database)" section and hit "Unblock" button it say: Unblocking has failed. So now i was forced to completely disable plugin to get access from that IP.

**Comment by codeling** [comment]
Can you show screenshots of the entries in the whitelist and the blocked list?
Something must prevent bfstop from recognizing the IP address as whitelisted, because for a whitelisted IP, all checks are skipped.

Maybe you can you tell me a bit more about your configuration? Also, please check the [bfstop log files](https://github.com/codeling/bfstop/wiki/FAQ#how-do-i-turn-on-logging) and the php/apache error logs if you have access!

**Comment by SuperSonic45** [comment]
It turned out user gave me wrong IP (there was an error in one digit), so all that time i am working with wrong IP. Now with right IP all working as it should. I am sorry for disturb.

**Comment by codeling** [comment]
Glad that the issue has been resolved, thanks for reporting this here!
