### ISSUE TITLE
'0 Call to a member function getKeyName() on bool' message

### ISSUE THREAD

**Issue by Stefano-Uni** [codeling/bfstop#182]
Dear All,
I am not a Joomla expert, I have taken charge of a Joomla site vers. 3.9.26, PHP Version 7.3.28. I need to insert a new ip address exception in the 'Allow list' section but the system returns the message '0 Call to a member function getKeyName() on bool' and prevents me from continuing. What can I do?
Thank you for your support.
Regards,
Stefano Muscatello

**Comment by codeling** [comment]
This issue has been fixed, see issue #181. I haven't found the time to publish a new release with this fix yet, this might take a while.
If you need this functionality quickly, you can manually apply the changes as shown here: https://github.com/codeling/com_bfstop/commit/c09f7833ca9e68a27f90a57b708024d1aaa0e9bc

**Comment by Stefano-Uni** [comment]
Hi, despite changing files in our site as in 
https://github.com/codeling/com_bfstop/commit/c09f7833ca9e68a27f90a57b708024d1aaa0e9bc
and adding our IP in site’s DB in whitelist, Brute Force continues to stop the Ip.
Could you please help us?

**Comment by codeling** [comment]
I would recommend checking this FAQ entry: https://github.com/codeling/bfstop/wiki/FAQ#what-can-i-do-if-something-doesnt-work-as-expected
Also check which IPs bfstop is actually blocking via the backend.
A common reason for bfstop blocking access for unexpected IPs or despite whitelisting, would be that your server is actually using some kind of loadbalancing (or you using some kind of proxy). There is no 100% certain way to determine the client's IP address in that scenario, so that the load balancer or proxy might end up blocked.
