### ISSUE TITLE
PHP 8.2 warning because of dynamic properties deprecation

### ISSUE THREAD

**Issue by otpfiste** [codeling/bfstop#207]
Hi,

running on J4 with PHP 8.2, I get the following deprecation warning:
"Deprecated: Creation of dynamic property plgSystembfstop::$notifier is deprecated in /plugins/system/bfstop/bfstop.php on line 193"

See also:
https://php.watch/versions/8.2/dynamic-properties-deprecated

All the best!

**Comment by codeling** [comment]
Thanks for reporting!
This has already been addressed in the repository, see https://github.com/codeling/bfstop/issues/197.
The fix is not yet included in a released version; if you can't wait to have this fixed, you can apply the changes mentioned in the issue linked above manually.
It will be included in the upcoming version 1.5.0, which is planned to come out end of December!
