### ISSUE TITLE
Joomla Updating error messsage

### ISSUE THREAD

**Issue by dimps1** [codeling/bfstop#95]
Hi,
I have recently installed BFStop on various sites and it works like a bomb. However if I want to check for updates via Joomla I always get this message:
Update: :Collection: Could not open https://raw.github.com/codeling/pkg_bfstop/master/update.xml
This is for Joomla 2.5.7, I do not get that message on 3.3.6
Any reason for this?
Thanks and regards

**Comment by codeling** [comment]
This will be fixed with the upcoming release 1.4.0.
The new URL for the update server is https://bfstop.bfroehler.info/update-pkg.xml.
You can already use that server, check the `#__update_sites` table for the entry containing the value `https://raw.github.com/codeling/pkg_bfstop/master/update.xml` and change it to `https://bfstop.bfroehler.info/update-pkg.xml`. Note that the server currently uses a cacert certificate, and therefore could cause problems regarding certificate trust.

The plan is to have a letsencrypt certificate until 1.4.0 version which will hopefully be accepted everywhere.

**Comment by codeling** [comment]
@dimps1 In case you haven't updated the update-server address in the database yet, there is a new release available: https://github.com/codeling/bfstop/releases/tag/1.4.1
The easiest way to upgrade is probably to install the pkg_bfstop-1.4.1.zip file via the backend.

Please comment here or open a new issue if you should still encounter any problems with that new version!

**Comment by dimps1** [comment]
Hi Bernhard,

 

Thanks very much, the update works straight from my websites with no problem. Just one question: It seems that the updates only shows 5 line items at a time, whereas before I could eyeball the whole lot at once. Useful when someone has managed to lock themselves out of a website, and I need to whitelist them.

 

Kind regards

Dile

 

2016_email_logo
spacer(011) 455-2910 | (083) 659-0661
dile@eye-q.co.za | www.eye-q.co.za

**Comment by codeling** [comment]
> Just one question: It seems that the updates only shows 5 line items at a time, whereas before I could eyeball the whole lot at once. Useful when someone has managed to lock themselves out of a website, and I need to whitelist them. 

I'm not sure whether that has changed recently, but all of the lists in the bfstop backend should use Joomla!'s default paging mechanism. The list size can therefore be specified in the global Joomla! site configuration (System -> Global Configuration -> Site tab, there the setting "Default List Limit").

**Comment by dimps1** [comment]
Thanks very much, I’ll check that out.

Have a good evening,

Kind regards

Dile

 

2016_email_logo
spacer(011) 455-2910 | (083) 659-0661
dile@eye-q.co.za | www.eye-q.co.za
